apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: spring-pg-k8s
build:
  artifacts:
    - image: andregs/spring-pg-k8s
      buildpacks:
        builder: paketobuildpacks/builder:tiny
        dependencies:
          paths:
            - src
            - pom.xml
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
